[package]
name = "zinc64"
version = "0.6.1-pre"
authors = ["Sebastian Jastrzebski <sebby2k@gmail.com>"]
description = "Commodore 64 emulator toolkit with batteries included but swappable"
license = "GPL-3.0+"
repository = "https://github.com/digitalstreamio/zinc64"
readme = "README.md"
keywords = ["c64", "commodore", "emulator"]
categories = ["emulators"]
exclude = [ "bin/*", "doc/*", "res/*" ]

[dependencies]
bit_field = "0.9"
byteorder = "1.2"
log = "0.3"
resid-rs = "0.7"

[profile.release]

[workspace]
members = [
    "zinc64-debug",
    "zinc64-loader",
    "zinc64-sdl",
]